build: off

environment:
  matrix:
    - PYTHON: "C:\\Python38-x64"
      PYTHON_ARCH: "64"

install:
  - SET PATH=%PYTHON%;%PATH%
  - python --version
  - python -m pip install -r requirements.txt

test_script:
  - set PYTHONUTF8=1
  - python setup.py test